### ISSUE TITLE
Info on this repo

### ISSUE THREAD

**Issue by BreakSecurity** [RfidResearchGroup/RFIDtools#1]
It is just an informative repo on the app you published on the play store or you will proceed releasing the source code of the app. It would be great 🥇

**Comment by BreakSecurity** [comment]
From twitter...
Quick teaser !
What does MCT, Pn532, Proxmark3, ChameleonMini, 122u have in common?


I hope you will release an app. One app to rule them all! ;)
@RfidResearchGroup

**Comment by iceman1001** [comment]
The idea is to release it as open source.   Lets see when the developer get it done.

**Comment by BreakSecurity** [comment]
And what about the ChameleonMini reboot?
