### ISSUE TITLE
Errors while building

### ISSUE THREAD

**Issue by grspy** [RfidResearchGroup/RFIDtools#11]
Upon opening the project with the latest Android Studio I'm getting the following errors:
1) `ERROR: RFIDtools\app\app.iml (The system cannot find the file specified)`
Along with warnings about other missing iml files (console.iml, crapto1.iml, freo.iml, etc.)
Creating an empty file app\app.iml is a dirty workaround for this.
2) `ERROR: Gradle project cmake.path is pm3rdv4rrg\src\main\cpp\CMakeLists.txt but that file doesn't exist`
Even if I manually git clone the RRG repo in the pm3rdv4rrg\src\main\cpp directory, still there is no CMakeLists.txt included.

**Comment by xianglin1998** [comment]
The project use gradle manage,  when compiling the release version, I added GUI keystore input function, which may have compatibility problems. If you encounter problems when compiling the release version, please cancel the keystore input function under the app module and enter your own keystore information.

**Comment by xianglin1998** [comment]
rdv4 module need fetch sourece from github.
