### ISSUE TITLE
Some bugs and some suggestions

### ISSUE THREAD

**Issue by Qaoyao** [RfidResearchGroup/RFIDtools#12]
1. Main page dragging view flashing(1plus 7)

2. Equipment detach requires restart app

3. Optimize the path selection of files, add and remove files in the form of labels, and try not to write them dead.

4. Android10 compatibility

**Comment by xianglin1998** [comment]
These problems have been collected and we will deal with them in the subsequent update. Thank you for your feedback. ：）

**Comment by jl-dos** [comment]
> These problems have been collected and we will deal with them in the subsequent update. Thank you for your feedback. ：）

+1 for android 10. Any documented issues around android 10 compatibility that could use help?

**Comment by xianglin1998** [comment]
Some bug fixed, so close.
