### ISSUE TITLE
PN533 based products compatibility

### ISSUE THREAD

**Issue by Mera-balou** [RfidResearchGroup/RFIDtools#18]
I tried the app with my ACR122u (PN532 based) and it works great.

I have also a PN533 based USB antenna which has better performance for NFC detection distance : [NFC RFID Reader Writer - DL533N XL](https://webshop.d-logic.net/products/nfc-rfid-reader-writer/dl533n-libnfc-series/dl533n-xl-oem.html). The antenna is fully supported by the open source library LibNFC, but unfortunately not by RFIDtools apk.

Would it be complicated to add the compatibility of PN533 hardware (already supported by LibNFC)?

By the way, I can't wait to receive your new ChameleonMini Rev G & ChameleonTiny...

**Comment by xianglin1998** [comment]
Hello Mera balou, for a new device addition (libnfc already exists), this is very simple, we only need to migrate the register driver and configuration, but recently we are maintaining chameleon's project, there is no time to add new device support, sorry. However, we can record this need and add support in later versions.

**Comment by xianglin1998** [comment]
PN533 test support will be released, please pay attention to the latest version update.
