### ISSUE TITLE
Update firmware to latest version or add building instructions

### ISSUE THREAD

**Issue by anonymix007** [RfidResearchGroup/RFIDtools#20]
With special Android firmware it's impossible to use Proxmark3 with Windows client as it version is outdated.
![image](https://user-images.githubusercontent.com/48598263/74592399-0b83df00-5032-11ea-80bc-2469e4e0d9da.png)

**Comment by xianglin1998** [comment]
The new rrg fw version(2020/02/11)  is adapted. Please pay attention to the recent version update (not released to the application market at present)
