### ISSUE TITLE
Errors while building

### ISSUE THREAD

**Issue by anonymix007** [RfidResearchGroup/RFIDtools#28]
Where is a list of errors in Android Studio:
![image](https://user-images.githubusercontent.com/48598263/76766091-844c9700-67a8-11ea-8216-af5b131394f1.png)

And in cmd (gradlew build):
![image](https://user-images.githubusercontent.com/48598263/76768810-98929300-67ac-11ea-9dc2-c9fc94abffd3.png)

**Comment by xianglin1998** [comment]
Hello, anonymix 007. The RFID tools project has changed a lot, so it can't be compatible with the old source code. You need to execute a complete "git clone" command, which should solve most of your problems. Thank you for your feedback.

**Comment by xianglin1998** [comment]
If you want to use a single module alone, please read the project code in detail, which will help you to extract the module.

**Comment by anonymix007** [comment]
> "git clone"

Okay, it helped.

> If you want to use a single module alone, please read the project code in detail, which will help you to extract the module.

And if I want to compile Proxmark3 firmware compatible with app what do I need to do? Are there any instructions?

**Comment by xianglin1998** [comment]
Now client can use cross compile. you can compile a linux executable file and pack to zip and update in assets/proxmark3.zip
