### ISSUE TITLE
Support for ChameleonTiny (Proxgrind) RevG ?

### ISSUE THREAD

**Issue by macrl2000** [RfidResearchGroup/RFIDtools#42]
When i use my Proxgrind Chameleon Tiny RevG (Firmware 11a8cc5 2020-02-03) with the latest Android Chameleon App from playstore all works well. When i try to open it in RFIDtools (also latest playstore) it finds a "OTGToUartSerial(OTG..)" 00:00:00:00:00:00. 
when pressing connect it stays forever in connecting.
So is there no support for Tiny/RevG device ? do i need other Firmware on Tiny
or are i doing something wrong ?

Kind Regards

**Comment by xianglin1998** [comment]
The RFID Tools is All Chameleon Reve.G unsupported ，The Chameleon Tiny & Chameleon Mini we have the another android application on work, see link:  https://play.google.com/store/apps/details?id=com.proxgrind.chameleon

**Comment by macrl2000** [comment]
thank you - yes i am using that "Chameleon App" already, just wanted to know whats the problem with RFIDtools. Thank you for pointing out !
