### ISSUE TITLE
Android 10 night mode makes the terminal unreadable

### ISSUE THREAD

**Issue by nvx** [RfidResearchGroup/RFIDtools#45]
My Pixel 2 running Android 10 has night mode enabled in system options. By default this makes compliant apps also use the night theme, including it seems RFID Tools.

The problem is it looks like the background in the terminal becomes dark as expected, but the text colour stays as a light grey which is almost impossible to read.

https://stackoverflow.com/a/60564184/1276877 suggests there might be a quick fix to simply force disable night mode in the app until proper support can be added.

**Comment by xianglin1998** [comment]
OK, we have the force disable night mode and use TERMUX terminal view. your thread can close.
