### ISSUE TITLE
Latest RFIDTools (10.apk) not working with latest proxmark code.

### ISSUE THREAD

**Issue by monster1025** [RfidResearchGroup/RFIDtools#46]
Latest RFIDTools (10.apk) not working with latest proxmark code (iceman edition, master branch).
It says invalid protocol version.
Proxmark is connected by USB.

CAPABILITIES_VERSION was changed to 5 and BigBufSize now present in protocol.
https://github.com/RfidResearchGroup/proxmark3/commit/291238a2f0b148690d154ba2391a8a32e11d1f7b#diff-3f754ec7b8a86af461003f72b79c42ba

**Comment by xianglin1998** [comment]
RFID Tools need to use new Terminal impl, such as Termux, Android Emulator.
So i must bring current CONSOLE view from SimpleConsoleView to FullTerminalView change first.

This is a big big big change, plz wait, after terminal view finish, the fw and client version will update sync.

**Comment by xianglin1998** [comment]
I provide the RRG branch with a complete cross compilation process. In the subsequent process, RFID tools will use the cross compiled executable to provide client services. This client can be compiled by the user himself. At that time, you will get a more complete terminal experience.

**Comment by xianglin1998** [comment]
@monster1025 The client and terminal view is updated.

Now you can run your RDV4 on app latest version.

So i can close this thread.

**Comment by monster1025** [comment]
Thanks a lot! =)

**Comment by xianglin1998** [comment]
Google play need some time to update, if you need app now, i can upload to repo release and you can goto download.

See: https://github.com/RfidResearchGroup/RFIDtools/releases/tag/v1.4.6

**Comment by xianglin1998** [comment]
This is a screenshot, is very nice terminal, go to download you can get it.

![2](https://user-images.githubusercontent.com/23152044/86228743-548f9680-bbc1-11ea-92fd-0b2d60ed61e2.png)

**Comment by monster1025** [comment]
Yep, got it - great, works like a charm! Terminal view is much cooler than before! Thank you again! =)
One thing is missing - quick commands button, but it is not a big problem =)

**Comment by xianglin1998** [comment]
Easy Button need some time to recovery,  if i have the time. :)

**Comment by monster1025** [comment]
Not a big problem, it works again, look much cooler and it is enough to have a great experience =)
