### ISSUE TITLE
Proxmark3 Easy 512M support

### ISSUE THREAD

**Issue by bluenazgul** [RfidResearchGroup/RFIDtools#52]
Please add support for the Proxmark3 easy 512M (running different Fimware's - almost all Firmware Version are able to run the same CLI Commands, some are able to read more tag as others but that could be detected by the firmware)

**Comment by xianglin1998** [comment]
Only PM3 RDV4 supported.

**Comment by lanrat** [comment]
My PM3 Easy with the latest Iceman firmware seems to be working fine with RFIDtools. (I know its not officially supported, but I'm happy it works ;) )

**Comment by UltrashRicco** [comment]
> My PM3 Easy with the latest Iceman firmware seems to be working fine with RFIDtools. (I know its not officially supported, but I'm happy it works ;) )

Oh, good to know, thanks!!

**Comment by UltrashRicco** [comment]
> My PM3 Easy with the latest Iceman firmware seems to be working fine with RFIDtools. (I know its not officially supported, but I'm happy it works ;) )

Even works with 256kb version of PM3 Easy, provided you skip some features when compiling the FW so that it fits when you flash it!

Wow, autopwn from my smartphone is so fast and convenient, this is incedible! Thank you all!
@lanrat @xianglin1998 @bluenazgul
