### ISSUE TITLE
Add support for changing the proxmark home directory

### ISSUE THREAD

**Issue by Ten0** [RfidResearchGroup/RFIDtools#53]
With the current configuration, log files and dump get stored to `/data/data/com.rfidresearchgroup.rfidtools/files/home`.
If you're not rooted, you cannot extract the dump files nor the log files. (or am I mistaken?)
It would be great to be allowed to configure a location for these two in the app settings.

**Comment by xianglin1998** [comment]
ok, i will add a opt on settings page, to change home path.

**Comment by xianglin1998** [comment]
I am iml, :)

@Ten0

seel: https://github.com/RfidResearchGroup/RFIDtools/releases/tag/v1.4.8
