### ISSUE TITLE
connection issues with an PM3 RDV4 over bluetooth

### ISSUE THREAD

**Issue by connect192168** [RfidResearchGroup/RFIDtools#56]
I'm using a Proxmark 3 RDV4 with the bluetooth module.

I've flashed the firmware listed here successfully : https://github.com/RfidResearchGroup/RFIDtools#proxmark3-firmware

I've connected my client device to the proxmark via bluetooth and the app.
My device is running android 10.
I'm using the latest version of the app (as of 1200 UTC on the 14th of September 2020)

When I connect to the device, it does display "Device init success"

I open up the termux terminal in the app and I get:
```
[!!] 🚨Capabilites structure version sent by Proxmark3 is not the same as the one used by the client!
[!!] 🚨Please flash the Proxmark with the same version as the client!
[!!] 🚨ERROR: cannot communicate with the Proxmark.
```

When I try the `Flash Firmware(OTG)` option, it says `Device not found(Proxmark3 CDC)`

Any help would be appreciated.

**Comment by xianglin1998** [comment]
The firmware from readme is very old(That is 20190812 complied).
I am sorry, i will update download link on readme at next update.
Now you can goto proxgrind website to download latest fw:
-> [Click to download](http://proxgrind.com/free-sdk/)

enjoy.

**Comment by connect192168** [comment]
After a small hiccup (downloading the one at the top of the list, flashing it and noticing my mistake), I downloaded and flashed the correct version (which was at the bottom of the list).
It worked perfectly.
Thank you for your help.
