### ISSUE TITLE
Provide recent builds as apk

### ISSUE THREAD

**Issue by vasilpetrov** [RfidResearchGroup/RFIDtools#89]
Last released apk is from 2020. It doesn't seems that release pipeline is properly maintained. Could you please provide more recent builds? Thanks

**Comment by rascapac** [comment]
Same

**Comment by vasilpetrov** [comment]
@iceman1001 is this project abandoned ?

**Comment by iceman1001** [comment]
I think you answered your own question.

**Comment by vasilpetrov** [comment]
This can be closed since I moved to a workaround with termux and building the client from source

**Comment by Ten0** [comment]
> This can be closed since I moved to a workaround with termux and building the client from source

Interesting!
How do you get termux access to the plugged proxmark?
Also how do you build it from source with android target?

**Comment by Ten0** [comment]
Aha [this](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/termux_notes.md)... ok that was so much simpler. Thanks!
